apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
     app: myjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
         app: myjavaapp
  template:
     metadata:
       labels:
         app: myjavaapp
     spec:
       containers:
       - name: myjavaapp-container
         image: nbktechnosys/myjavaapp19jun22:2 
         resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2" 
         ports:
         - containerPort: 8080